apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-1qry
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ociz-tenant/rhtap-demo-app/hacbs-test-project-1qry@sha256:68d95e0dc11705de2755fd2dce5f1ca304585acaa51f7c7b7f138bf7dbf99581
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
