apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-1qry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-1qry
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-1qry
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-1qry
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-1qry
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ociz-tenant/rhtap-demo-app/hacbs-test-project-1qry@sha256:16af6ec03f6d0a552a26b5cde73fea26970ff857ca96906d3f0c93cde78f3a9f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
